### ISSUE TITLE
Tests and Implementation

### ISSUE THREAD

**Issue by danielfoglio** [cratekube/lifecycle-service#6]
### Acceptance Criteria
The `lifecycle-service` 
- Exposes component upgrade availability.
- Can upgrade managed components, including itself.
- Secures create/modify REST resources.

### Documentation
Documentation for this service will be covered as part of the documentation for CrateKube as a whole in cratekube/cratekube#32

### When is this feature complete?
- [x] Automated unit tests must cover 100% of the documented contracts
- [x] Automated integration tests must cover the sanity use cases
- [x] The `lifecycle-service` implementation possesses all functionality from Acceptance Criteria
- [x] User facing documentation has been created

### Links / references
Architecture Design story: https://github.com/cratekube/cratekube/issues/10
This is one of the components for the CrateKube MVP: https://github.com/cratekube/cratekube/blob/master/docs/Architecture.md#lifecycleservice

**Comment by pdgrenon** [comment]
Moved the documentation of this service to cratekube/cratekube#32
